version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=movies_dbuser
      - POSTGRES_PASSWORD=P@ssw0rd1
      - POSTGRES_DB=movies
    ports:
      - 5432:5432